[project]
name = "papermatch-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub>=0.32.4",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "umap>=0.1.1",
]
